name: Firebase Cloud Hosting Synchronizer
on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  hosting-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Node
        uses: actions/checkout@v4

      - name: Align Node Runtime Version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Fetch Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Deploy to Firebase hosting channels
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IBNE_RATUL_CYBER }}'
          channelId: live
          projectId: ismail-ibne-ratul
